### ISSUE TITLE
Missing imports (easy to fix)

### ISSUE THREAD

**Issue by ingstra** [quantshah/qst-cgan#2]
paper-figures/fig4-wigner.ipynb commit d415953a1e740dae0d1ea4d98c29fde6041dba7d. 
Errors already in the second cell:

`NameError: name 'coherent' is not defined`
`NameError: name 'Qobj' is not defined`

**Comment by quantshah** [comment]
Aha thanks. VSCode seems to not look at the whole notebook before specifying if there are unused imports. I will fix them (or you're welcome to make a PR :-))
